# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "bento/centos-6.7"
  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.provider "virtualbox" do |v|
     v.customize ["modifyvm", :id, "--memory", 1024, "--cpus", 1, "--name", "one-click-deploy-dev"]
  end
end
