---
- name: Install httpd
  yum: name=httpd state=present
  tags: httpd
  
- name: Install mod_ssl
  yum: name=mod_ssl state=present
  tags: mod_ssl

- name: copy ssl conf file
  template:
      src=ssl.conf.j2
      dest=/etc/httpd/conf.d/ssl.conf
      mode=644

- name: Stop httpd
  service: name=httpd state=stopped

- name: Start httpd
  service: name=httpd state=started enabled=yes

